require('dotenv').config();
const express=require('express');
const session=require('express-session');
const cors=require('cors');
const path=require('path');
const db=require('./db');
const authRoutes=require('./routes/auth');
const orderRoutes=require('./routes/orders');
const companyRoutes=require('./routes/company');
const garmentRoutes=require('./routes/garments');
const sectionRoutes=require('./routes/sections');
const qrRoutes=require('./routes/qr');
const staffRoutes=require('./routes/staff');
const storageRoutes=require('./routes/storage');
const exportRoutes=require('./routes/export');
const workflowRoutes=require('./routes/workflow');
const shareRoutes=require('./routes/share');
const PgSessionStore=require('./session-store');
const app=express();
app.set('trust proxy',1);
app.use(express.json({limit:'35mb'}));
app.use(cors({origin:process.env.CORS_ORIGIN||true,credentials:true}));
app.use(session({store:new PgSessionStore(db),secret:process.env.SESSION_SECRET||'change-this-secret-before-going-live',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:'auto',maxAge:1000*60*60*12}}));
app.use('/api/auth',authRoutes);app.use('/api/orders',orderRoutes);app.use('/api/company',companyRoutes);app.use('/api/garments',garmentRoutes);app.use('/api/sections',sectionRoutes);app.use('/api/qr',qrRoutes);app.use('/api/staff',staffRoutes);app.use('/api/storage',storageRoutes);app.use('/api/export',exportRoutes);app.use('/api/workflow',workflowRoutes);app.use('/api/share',shareRoutes);app.get('/bill/:token',(req,res,next)=>{req.url='/public/'+req.params.token;shareRoutes.handle(req,res,next);});
app.use(express.static(path.join(__dirname,'public')));app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
const PORT=process.env.PORT||3000;
db.initDb().then(()=>app.listen(PORT,()=>console.log(`MM Javeed Couture backend running on port ${PORT}`))).catch(err=>{console.error('Database startup failed:',err);process.exit(1);});
