const express=require('express');
const db=require('../db');
const {requireAuth}=require('../middleware/auth');
const router=express.Router();
async function nextSeq(key,start){const c=await db.pool.connect();try{await c.query('BEGIN');let r=(await c.query('SELECT value FROM meta WHERE key=$1 FOR UPDATE',[key])).rows[0];const cur=r?parseInt(r.value,10):start;await c.query('INSERT INTO meta(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value',[key,String(cur+1)]);await c.query('COMMIT');return cur}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
async function getOrCreateCustomer(name,phone,address){const digits=(phone||'').replace(/\D/g,'');let c=null;if(digits)c=(await db.query("SELECT * FROM customers WHERE regexp_replace(COALESCE(phone,''),'[^0-9]','','g') LIKE $1 LIMIT 1",['%'+digits+'%'])).rows[0];if(!c&&name)c=(await db.query("SELECT * FROM customers WHERE lower(name)=lower($1) AND COALESCE(phone,'')='' LIMIT 1",[name])).rows[0];if(c){await db.query('UPDATE customers SET name=$1,phone=$2,address=$3 WHERE id=$4',[name||c.name,phone||c.phone,address||c.address,c.id]);return (await db.query('SELECT * FROM customers WHERE id=$1',[c.id])).rows[0]}const seq=await nextSeq('customer_seq',1);return (await db.query('INSERT INTO customers(customer_code,name,phone,address) VALUES($1,$2,$3,$4) RETURNING *',['MMJBR'+String(seq).padStart(3,'0'),name||'Walk-in Customer',phone||'',address||''])).rows[0]}
async function rowToOrder(row){const c=(await db.query('SELECT * FROM customers WHERE id=$1',[row.customer_id])).rows[0];return {id:row.order_no,date:row.date,client:{name:c?.name||'',contact:c?.phone||'',address:c?.address||''},customerId:c?.customer_code||'',items:JSON.parse(row.items_json||'[]'),materials:JSON.parse(row.materials_json||'[]'),measurements:JSON.parse(row.measurements_json||'{}'),customFields:JSON.parse(row.custom_fields_json||'{}'),trialDate:row.trial_date,deliveryDate:row.delivery_date,tailorName:row.tailor_name,notes:row.notes,subtotal:+row.subtotal||0,itemDiscount:+row.item_discount||0,overallDiscount:+row.additional_discount||0,discountPercent:+row.additional_discount||0,gst:5,grandTotal:+row.grand_total||0,paymentReceived:+row.payment_received||0,paymentMode:row.payment_mode,balance:+row.balance||0,deliveryStatus:row.delivery_status||'Not Delivered',createdBy:row.created_by||''}}
function calc(b,role){const subtotal=+(b.subtotal||0);let pct=+(b.discountPercent??b.overallDiscount??0);if(pct<0)pct=0;if(role==='staff'&&pct>15)throw Object.assign(new Error('Staff discount cannot exceed 15%'),{status:400});const discounted=Math.max(subtotal*(1-pct/100),0);const grand=Math.round(discounted*1.05*100)/100;const received=+(b.paymentReceived||0);return {subtotal,pct,grand,received,balance:Math.max(Math.round((grand-received)*100)/100,0)}}
router.get('/',requireAuth,async(req,res)=>{try{const rows=(await db.query('SELECT * FROM orders ORDER BY id DESC')).rows;res.json(await Promise.all(rows.map(rowToOrder)))}catch(e){console.error(e);res.status(500).json({error:'Could not load orders'})}});
router.get('/:orderNo',requireAuth,async(req,res)=>{try{const r=(await db.query('SELECT * FROM orders WHERE order_no=$1',[req.params.orderNo])).rows[0];if(!r)return res.status(404).json({error:'Order not found'});res.json(await rowToOrder(r))}catch(e){res.status(500).json({error:'Could not load order'})}});
router.post('/',requireAuth,async(req,res)=>{try{const b=req.body||{},x=calc(b,req.session.user.role),c=await getOrCreateCustomer(b.client?.name,b.client?.contact,b.client?.address),orderNo='ORD-'+await nextSeq('order_seq',1001);const r=(await db.query(`INSERT INTO orders(order_no,customer_id,date,trial_date,delivery_date,tailor_name,notes,items_json,materials_json,measurements_json,custom_fields_json,subtotal,item_discount,additional_discount,gst_percent,grand_total,payment_received,payment_mode,balance,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,0,$13,5,$14,$15,$16,$17,$18) RETURNING *`,[orderNo,c.id,new Date().toISOString().slice(0,10),b.trialDate||'',b.deliveryDate||'',b.tailorName||'',b.notes||'',JSON.stringify(b.items||[]),JSON.stringify(b.materials||[]),JSON.stringify(b.measurements||{}),JSON.stringify(b.customFields||{}),x.subtotal,x.pct,x.grand,x.received,b.paymentMode||'Cash',x.balance,req.session.user.id])).rows[0];res.status(201).json(await rowToOrder(r))}catch(e){console.error(e);res.status(e.status||500).json({error:e.message||'Could not create order'})}});
router.put('/:orderNo',requireAuth,async(req,res)=>{try{const old=(await db.query('SELECT * FROM orders WHERE order_no=$1',[req.params.orderNo])).rows[0];if(!old)return res.status(404).json({error:'Order not found'});if(req.session.user.role==='staff'){const a=(await db.query("SELECT * FROM bill_edit_requests WHERE order_no=$1 AND staff_id=$2 AND status='approved' ORDER BY id DESC LIMIT 1",[req.params.orderNo,req.session.user.id])).rows[0];if(!a)return res.status(403).json({error:'Admin approval is required before editing this saved bill'});}
 const b=req.body||{},x=calc(b,req.session.user.role),c=await getOrCreateCustomer(b.client?.name,b.client?.contact,b.client?.address);const r=(await db.query(`UPDATE orders SET customer_id=$1,trial_date=$2,delivery_date=$3,tailor_name=$4,notes=$5,items_json=$6,materials_json=$7,measurements_json=$8,custom_fields_json=$9,subtotal=$10,item_discount=0,additional_discount=$11,gst_percent=5,grand_total=$12,payment_received=$13,payment_mode=$14,balance=$15,updated_at=NOW() WHERE id=$16 RETURNING *`,[c.id,b.trialDate||'',b.deliveryDate||'',b.tailorName||'',b.notes||'',JSON.stringify(b.items||[]),JSON.stringify(b.materials||[]),JSON.stringify(b.measurements||{}),JSON.stringify(b.customFields||{}),x.subtotal,x.pct,x.grand,x.received,b.paymentMode||'Cash',x.balance,old.id])).rows[0];const newBill=await rowToOrder(r);if(req.session.user.role==='staff')await db.query("UPDATE bill_edit_requests SET status='used',used_at=NOW() WHERE id=(SELECT id FROM bill_edit_requests WHERE order_no=$1 AND staff_id=$2 AND status='approved' ORDER BY id DESC LIMIT 1)",[req.params.orderNo,req.session.user.id]);res.json(newBill)}catch(e){console.error(e);res.status(e.status||500).json({error:e.message||'Could not update order'})}});

router.put('/:orderNo/delivery-status',requireAuth,async(req,res)=>{
  try{
    const status=String(req.body?.status||'').trim();
    if(!['Delivered','Not Delivered'].includes(status)){
      return res.status(400).json({error:'Invalid delivery status'});
    }
    const row=(await db.query(
      'UPDATE orders SET delivery_status=$1,updated_at=NOW() WHERE order_no=$2 RETURNING *',
      [status,req.params.orderNo]
    )).rows[0];
    if(!row)return res.status(404).json({error:'Order not found'});
    res.json(await rowToOrder(row));
  }catch(e){
    console.error(e);
    res.status(500).json({error:'Could not update delivery status'});
  }
});

router.delete('/:orderNo',requireAuth,async(req,res)=>{try{if(req.session.user.role!=='admin')return res.status(403).json({error:'Only Admin can delete bills'});const r=(await db.query('DELETE FROM orders WHERE order_no=$1 RETURNING id',[req.params.orderNo])).rows[0];if(!r)return res.status(404).json({error:'Order not found'});res.status(204).end()}catch(e){res.status(500).json({error:'Could not delete order'})}});
module.exports=router;
