const express=require('express');
const bcrypt=require('bcryptjs');
const db=require('../db');
const {requireAuth,requireAdmin}=require('../middleware/auth');
const router=express.Router();
async function listStaff(){return (await db.query("SELECT id, login_id AS \"loginId\", name FROM users WHERE role='staff' ORDER BY id ASC")).rows;}
router.get('/',requireAuth,requireAdmin,async(req,res)=>{try{res.json(await listStaff())}catch(e){console.error(e);res.status(500).json({error:'Could not load staff'})}});
router.post('/',requireAuth,requireAdmin,async(req,res)=>{try{const{name,loginId,password}=req.body||{};if(!name||!loginId||!password)return res.status(400).json({error:'Name, login ID and password are all required'});if(password.length<6)return res.status(400).json({error:'Password must be at least 6 characters'});const clash=(await db.query('SELECT id FROM users WHERE lower(login_id)=lower($1)',[loginId.trim()])).rows[0];if(clash)return res.status(409).json({error:'That login ID is already in use'});await db.query('INSERT INTO users (login_id,password_hash,role,name) VALUES ($1,$2,$3,$4)',[loginId.trim(),bcrypt.hashSync(password,10),'staff',name.trim()]);res.status(201).json(await listStaff())}catch(e){console.error(e);res.status(500).json({error:'Could not add staff'})}});
router.put('/:id',requireAuth,requireAdmin,async(req,res)=>{try{const existing=(await db.query("SELECT * FROM users WHERE id=$1 AND role='staff'",[req.params.id])).rows[0];if(!existing)return res.status(404).json({error:'Staff account not found'});const{name,loginId,password}=req.body||{};const finalLoginId=(loginId||existing.login_id).trim();if(!finalLoginId)return res.status(400).json({error:'Login ID cannot be empty'});const clash=(await db.query('SELECT id FROM users WHERE lower(login_id)=lower($1) AND id<>$2',[finalLoginId,existing.id])).rows[0];if(clash)return res.status(409).json({error:'That login ID is already in use'});if(password){if(password.length<6)return res.status(400).json({error:'Password must be at least 6 characters'});await db.query('UPDATE users SET login_id=$1,name=$2,password_hash=$3 WHERE id=$4',[finalLoginId,(name||existing.name||'').trim(),bcrypt.hashSync(password,10),existing.id]);}else{await db.query('UPDATE users SET login_id=$1,name=$2 WHERE id=$3',[finalLoginId,(name||existing.name||'').trim(),existing.id]);}res.json(await listStaff())}catch(e){console.error(e);res.status(500).json({error:'Could not update staff'})}});
router.delete('/:id',requireAuth,requireAdmin,async(req,res)=>{try{const existing=(await db.query("SELECT * FROM users WHERE id=$1 AND role='staff'",[req.params.id])).rows[0];if(!existing)return res.status(404).json({error:'Staff account not found'});await db.query('DELETE FROM users WHERE id=$1',[existing.id]);res.json(await listStaff())}catch(e){console.error(e);res.status(500).json({error:'Could not delete staff'})}});
module.exports=router;
